# Site settings
title: Coding with Kristina
header-img: img/home-bg.png
email: ksenesaynho@gmail.com
copyright_name: ksenesaynho
description: > # this means to ignore newlines until "baseurl:"
  My journey through coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ksenesaynho
learn_profile: ksenesaynho
email_username: ksenesaynho@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
